<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DumpStrings</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>C:\Users\34294\.nuget\packages\mono.cecil\0.11.6\lib\netstandard2.0\Mono.Cecil.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
